name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy-ui:
    name: Build and Deploy UI to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Install Dependencies and Build React app
        run: |
          cd frontend/marmotblog
          npm install
          npm run build 

      - name: Sync UI to S3
        run: |
          aws s3 sync frontend/marmotblog/build/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

# uncomment once the BE code is defined
#  deploy-service1-lambdas:
#    name: Deploy service1 lambdas
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-2
#
#      - name: Deploy each lambda in service1
#        run: |
#          for lambda_dir in services/service1/*; do
#            if [ -d "$lambda_dir" ]; then
#              lambda_name=$(basename "$lambda_dir")
#              echo "Deploying $lambda_name"
#
#              zip -r /tmp/${lambda_name}.zip "$lambda_dir"
#
#              aws lambda update-function-code \
#                --function-name "$lambda_name" \
#                --zip-file "fileb:///tmp/${lambda_name}.zip"
#            fi
#          done

# a gateway isn't needed for the root route, so comment out until needed for BE
#  deploy-api-gateway:
#    name: Deploy OpenAPI to API Gateway
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-2
#
#      - name: Deploy OpenAPI specification
#        run: |
#          api_id=${{ secrets.API_GATEWAY_ID }}
#          aws apigateway put-rest-api \
#            --rest-api-id $api_id \
#            --mode overwrite \
#            --body fileb://api/openapi.yaml
#
#          aws apigateway create-deployment \
#            --rest-api-id $api_id \
#            --stage-name production
